---
- name: Set password on all DNS hosts
  hosts: dns
  become: true

  # Need the config for anything?
  #vars_files:
  #  - default.config.yml

  tasks:
    - name: Maybe fail if missing password env variables
      ansible.builtin.fail: 
        msg: Env vars DNS1_PWD and DNS2_PWD must be set to get proceed
      vars:
        has_dns1_pwd: lookup('ansible.builtin.env', 'DNS1_PWD') | length > 0
        has_dns2_pwd: lookup('ansible.builtin.env', 'DNS2_PWD') | length > 0
      when: 
        - (not has_dns1_pwd or not has_dns2_pwd)

    - name: Maybe set password for primary DNS
      ansible.builtin.shell:
        cmd: "pihole setpassword '{{ dns1_pwd }}'"
      vars:
        dns1_pwd: "{{ lookup('ansible.builtin.env', 'DNS1_PWD') }}"
      when: node_name == "dns1"
      register: setpassword_result

    - name: Maybe set password for secondary DNS
      ansible.builtin.shell:
        cmd: "pihole setpassword '{{ dns2_pwd }}'"
      vars:
        dns2_pwd: "{{ lookup('ansible.builtin.env', 'DNS2_PWD') }}"
      when: node_name == "dns2"
