---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian13-ansible:latest
    published_ports:
      - "127.0.0.1:8080:8080/tcp"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - primary
      - dns
provisioner:
  name: ansible
  env:
    GLOBAL_BECOME: false  # Must set to false of molecule freaks out
    BLOCK_REMOTE_SET_URL_SSH: true
  inventory:
    host_vars:
      instance:
        node_name: dns1
